boxing/urls.py
from django.urls import path
from . import views

app_name = "boxing"

urlpatterns = [
    path('', views.boxing, name="menu"),
    path('tag/', views.tag, name="tag"),
    path('non_tag/', views.non_tag, name="nontag"),
    path('save_img/', views.save_img, name="save_img"),
    path('save_position/<int:image_pk>/', views.save_position, name="save_position"),
    path('save_tag_position/<int:image_pk>/', views.save_tag_position, name="save_tag_position"),
]

taging/urls.py
from django.urls import path
from . import views

app_name = "taging"

urlpatterns = [
    path('images/', views.images, name="images"),
    path('addtag/<int:image_pk>/', views.addtag, name="addtag"),
    path('test/', views.test, name="test"),
    
]

web_leb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('mainpage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boxing/', include('boxing.urls')),
    path('taging/', include('taging.urls')),
    path('ranking/', include('ranking.urls')),
    path('yesorno/', include('yesorno.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.db.models import constraints
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from accounts.models import User

# Create your models here.
# user.pk => company name??
# def articles_image_path(instance, filename):
#     return f'user_{instance.user.pk}/{filename}'

class Image(models.Model):
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(800, 600)],
        format='JPEG',
        options={'quality':90}
    )
    # 생성된 후 오랫동안 분석이 완료 되지 않은 이미지 검출용
    created_at = models.DateTimeField(auto_now_add=True)
    # 분석 (완료 / 진행) 등
    status = models.PositiveSmallIntegerField()
    tags = models.ManyToManyField('Tag', through='ImageUserTagBox')
    #filename = models.CharField(max_length=150)

class Box(models.Model):
    #좌측 상단 x,y ? 
    lefttopx = models.PositiveSmallIntegerField()
    lefttopy = models.PositiveSmallIntegerField()
    #우측 하단 x,y ?
    rightbotx = models.PositiveSmallIntegerField()
    rightboty = models.PositiveSmallIntegerField()
    # 1:M 구조
    #source_img = models.ForeignKey(Image, on_delete=models.CASCADE)
    #maker_userid = models.ForeignKey(User.username, on_delete=models.CASCADE)

class Tag(models.Model):
    # 태그 내용(유니크 제약 조건)
    # 중복되는 것은 Image-Tag-Username으로 묶어서 추가
    name = models.CharField(max_length=30, unique=True)
    #source_img = models.ForeignKey(Image, on_delete=models.CASCADE)
    #maker_userid = models.ForeignKey(User.username, on_delete=models.CASCADE)

class ImageUserTagBox(models.Model):
    # image, user는 not null
    # image-tag 일 경우 box=null
    # image-box 일 경우 tag=null
    # point는 선택 (받은 / 받지 못한) 횟수 +- 카운트
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default='DELETED_ACCOUNT')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, null=True)
    box = models.ForeignKey(Box, on_delete=models.CASCADE, null=True)
    point = models.IntegerField(default=0)
    class Meta:
        constraints = [
            #한 명의 사람은 한 개의 이미지에 같은 태그를 하나만 달 수 있도록
            #(ex:'A'라는 사람은 'IMAGE1.jpg'에 '사람'이라는 태그를 하나만 달 수 있음)
            models.UniqueConstraint(fields=['image', 'tag', 'user', 'box'], name='unique_imagetaguserbox'),
        ]

# class ImageBoxUser(models.Model):
#     image = models.ForeignKey(Image, on_delete=models.CASCADE)
#     box = models.ForeignKey(Tag, on_delete=models.CASCADE, null=True)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)

# A ㄱ 1
#   ㄴ 2
# B ㄱ 3
#   ㅇ 1
# Reservation.objects.all()
# <QuerySet [<Reservation: 1번 의사, 의사가나다의 1번 환자, 환자라마바와 간호사:간호사사자차>]>

# Reservation.objects.filter(doctor__name='의사가나다')
# <QuerySet [<Reservation: 1번 의사, 의사가나다의 1번 환자, 환자라마바와 간호사:간호사사자차>]>

taging/models.py
from django.db import models

# Create your models here.

images/views.py
from django.shortcuts import render

# Create your views here.

taging/views.py
from django.shortcuts import render, redirect
import os
import random
from django import template
from django.conf import settings
from images.models import Image, Tag, ImageUserTagBox
from accounts.models import User
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum

# Create your views here.
@login_required
def images(request):
    image = Image.objects.order_by('?').first()
    context = {
        #'image' : image.image.url,
        'image' : image.image_thumbnail.url,
        'image_pk' : image.pk
    }
    return render(request, 'taging/images.html',context)

@login_required
@require_POST
def addtag(request, image_pk):
    user = User.objects.get(username=request.user)
    image = Image.objects.get(pk=image_pk)

    datalen = len(list(request.POST))
    datalist = request.POST.getlist('tag')
    for data in datalist:
        try:
            #tag = Tag.objects.filter(name=data)
            tag = Tag.objects.get(name=data)
        except:
            tag = Tag.objects.create(name=data)
        imagetag = ImageUserTagBox.objects.create(user=user,image=image,tag=tag)

    return redirect('taging:images')

def test(request):
    # delimage = Image.objects.filter(image='')
    # delimage.delete()
    # print(delimage)
    image = Image.objects.order_by('?').first()
    tags = image.tags.annotate(tag_count=Sum('name')).order_by('-tag_count')
    context = {
        'image' : image.image.url,
        'tags' : tags
    }
    return render(request, 'taging/test.html', context)

taging/templates/taging/images.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <style>
        body {
            background-color: #0f0f1c !important;
            color: black;
        }
        .container {
            width: 100%;
            height: 100%;
            padding: 0 3em;
            background: #0f0f1c;
        }
        .img {
            margin: auto;
             border:5px solid black;
             display: inline-block;
             background-repeat: no-repeat;
             background-size: contain;
            width: auto;
            height: auto;
            max-width: 540px !important;
            max-height: 400px !important;
         }
         .p-button {
            margin-top: 0.5rem;
            text-align: center;
         }
         .row {
            /* background-color: #673AB7; */
         }
         #add-tag {
            margin-right: 10px;
         }
         
         input {
            background-color: inherit;
            border: 2px solid #f80;
            border-radius: 5px;
            color: black;
            margin: 1rem;
         }

        .typowriter{
            margin: 0px !important;
            text-align: center;
         }
        
        #typoimg {
            margin: 0px !important;
        }

        .paperarea{
            width: 549.36px;
            margin: auto;
            padding: 3px;
            background-color: #f6f7f9;
            font: 24px/24px 'Black Han Sans', sans-serif;
            color: #f80;
            text-transform: uppercase;
            text-align: center;
        }

        span{
            padding-left: 50px;
            padding-right: 50px;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
{% endblock %}
{% block body %}
<div class="content">
    <h1 class="retro txtcenter">사물 찾기</h1>
    <div class="paperarea">
        <img class="img" src="{{ image }}" alt="">
        <form action="{% url 'taging:addtag' image_pk %}" method="POST" id="inputform" style="display: inline-block;">
            {% csrf_token %}
            <p class="p-button">
                <button class="freebtn sub" type="button" id="add-tag">태그 추가</button>
                <button class="freebtn" type="submit">제출</button>
            </p>
            <p style="margin-bottom: 1rem;">
                <input id="tag-input-1" type="text" name="tag" required>
                <a id="deltag1" value="tag1">삭제</a>
            </p>
        </form>
    </div>
    <div class="typowriter">
        <img id="typoimg" src="{% static '/images/typo.png' %}" alt="">
    </div>
</div>
    <script>
        const typowidth = document.querySelector('#typoimg').width
        const paper = document.querySelector('.paperarea')
        // paper.style.width = (typowidth*0.63)+'px'

        let cnt = 1
        const delbutton = document.querySelector('#deltag1')
        delbutton.addEventListener('click', function(event){
            document.querySelector('#tag-input-1').remove()
            delbutton.remove()
        })   
        const btnAddTag = document.querySelector('#add-tag')
        btnAddTag.addEventListener('click', function(event) {
            const len = document.querySelectorAll('input').length
            if(len <= 4){
                const inputform  = document.querySelector('#inputform')
                const pTag = document.createElement('p')
                const inputTag = document.createElement('input')
                inputTag.type="text"
                inputTag.required = true
                inputTag.id='tag-input-'+(cnt+1)
                inputTag.name="tag"
                // inputTag.name="tag"+(cnt+1)

                const delTag = document.createElement('a')
                delTag.innerHTML = ' 삭제'
                delTag.addEventListener('click', function(event){
                    inputTag.remove()
                    delTag.remove()
                    cnt = cnt - 1
                })
                
                // const emTag = document.createElement('em')
                // emTag.innerText = (cnt+1)+')'

                inputform.append(pTag)
                // pTag.append(emTag)
                pTag.appendChild(inputTag)
                pTag.appendChild(delTag)
                cnt = cnt+1

            }else{
                alert('Tag는 최대 4개까지 추가할 수 있습니다!')
            }
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% endblock %}

taging/templates/taging/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="{{ image }}" alt="">
    {% for tag in tags %}
        <h1>{{tag.pk}}</h1>
        <p>{{ tag.name }}</p>
        <p>{{ tag.tag_count }}</p>
    {% endfor %}
    
</body>
</html>