boxing/urls.py
from django.urls import path
from . import views

app_name = "boxing"

urlpatterns = [
    path('', views.boxing, name="menu"),
    path('tag/', views.tag, name="tag"),
    path('non_tag/', views.non_tag, name="nontag"),
    path('save_img/', views.save_img, name="save_img"),
    path('save_position/<int:image_pk>/', views.save_position, name="save_position"),
    path('save_tag_position/<int:image_pk>/', views.save_tag_position, name="save_tag_position"),
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
]

ranking/urls.py
from django.urls import path
from . import views

app_name = 'ranking'

urlpatterns = [
    path('', views.ranking, name='ranking'),
    #path('week/', views.weekranking, name='weekranking')
]

taging/urls.py
from django.urls import path
from . import views

app_name = "taging"

urlpatterns = [
    path('images/', views.images, name="images"),
    path('addtag/<int:image_pk>/', views.addtag, name="addtag"),
    path('test/', views.test, name="test"),
    
]

web_leb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('mainpage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boxing/', include('boxing.urls')),
    path('taging/', include('taging.urls')),
    path('ranking/', include('ranking.urls')),
    path('yesorno/', include('yesorno.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yesorno/urls.py
from django.urls import path
from . import views

app_name = "yesorno"

urlpatterns = [
    path('', views.yesnoinfo, name="yesnoinfo"),
    path('right/', views.rightobj, name="rightobj"),
    path('wrong/', views.wrongobj, name="wrongobj"),
]

mainpage/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'mainpage/index.html')

mainpage/templates/mainpage/index.html
{% extends 'base.html' %}
{% load static %}
{% block head%}
    <link rel="stylesheet" href="{% static 'mainpage/css/mainpage.css' %}">
    <style>
      .mglr{
        margin-left: 15rem;
        margin-right: 15rem;
      }
    </style>
{% endblock %}
{% block body%}

<div class="content">
  <div>
      <h1 class="retro">그림 네모치기 레-츠고</h1>
      <h1 class="retro">재 미 있 읍 니 다 !</h1>
      <img src="{% static 'mainpage/images/mainimage.jpg' %}" alt="" width="500rem">
  </div>
  <div class="row mglr">
    <div class='wrapper'>
        <div role='button' class='retro-btn danger'>
        <a class='btn btntest' href="{% url 'taging:images' %}">
            <span class='btn-inner'>
            <span class='content-wrapper'>
                <span class='btn-content'>
                <span class='btn-content-inner' label="">
                    <h3 class="retro middle-size-font">사물 찾기</h3>
                    <h3 class="retro middle-size-font">BEGIN</h3>
                </span>
                </span>
            </span>
            </span>
        </a>
        </div>
    </div>
    <div class='wrapper'>
      <div role='button' class='retro-btn warning'>
        <a class='btn btntest' href="{% url 'boxing:menu' %}"> 
          <span class='btn-inner'>
            <span class='content-wrapper'>
              <span class='btn-content'>
                <span class='btn-content-inner' label="">
                  <h3 class="retro middle-size-font">숨은 그림 찾기</h3>
                  <h3 class="retro middle-size-font">BEGIN</h3>
                </span>
              </span>
            </span>
          </span>
        </a>
      </div>
    </div>
    <div class='wrapper'>
      <div role='button' class='retro-btn success'>
        <a class='btn btntest' href="{% url 'yesorno:yesnoinfo' %}"> 
          <span class='btn-inner'>
            <span class='content-wrapper'>
              <span class='btn-content'>
                <span class='btn-content-inner' label="">
                  <h3 class="retro middle-size-font">YES or NO</h3>
                  <h3 class="retro middle-size-font">BEGIN</h3>
                </span>
              </span>
            </span>
          </span>
        </a>
      </div>
    </div>
    <div class='wrapper'>
      <div role='button' class='retro-btn info'>
        <a class='btn btntest' href="{% url 'ranking:ranking' %}"> 
          <span class='btn-inner'>
            <span class='content-wrapper'>
              <span class='btn-content'>
                <span class='btn-content-inner' label="">
                  <h3 class="retro middle-size-font">RANKING</h3>
                  <h3 class="retro middle-size-font">BEGIN</h3>
                </span>
              </span>
            </span>
          </span>
        </a>
      </div>
    </div>
    <!-- <div class="col-sm-3">
      <div class='wrapper'>
          <div role='button' class='retro-btn warning'>
            <a class='btn btntest' href="{% url 'boxing:menu' %}"> 
              <span class='btn-inner'>
                <span class='content-wrapper'>
                  <span class='btn-content'>
                    <span class='btn-content-inner' label="">
                      <h3 class="retro middle-size-font">숨은 그림 찾기</h3>
                      <h3 class="retro middle-size-font">BEGIN</h3>
                    </span>
                  </span>
                </span>
              </span>
            </a>
          </div>
      </div>
  </div>
  <div class="col-sm-3">
      <div class='wrapper'>
          <div role='button' class='retro-btn success'>
            <a class='btn btntest' href="{% url 'yesorno:yesnoinfo' %}"> 
              <span class='btn-inner'>
                <span class='content-wrapper'>
                  <span class='btn-content'>
                    <span class='btn-content-inner' label="">
                      <h3 class="retro middle-size-font">YES or NO</h3>
                      <h3 class="retro middle-size-font">BEGIN</h3>
                    </span>
                  </span>
                </span>
              </span>
            </a>
          </div>
      </div>
  </div>
  <div class="col-sm-3">
      <div class='wrapper'>
          <div role='button' class='retro-btn info'>
            <a class='btn btntest' href="{% url 'ranking:ranking' %}"> 
              <span class='btn-inner'>
                <span class='content-wrapper'>
                  <span class='btn-content'>
                    <span class='btn-content-inner' label="">
                      <h3 class="retro middle-size-font">RANKING</h3>
                      <h3 class="retro middle-size-font">BEGIN</h3>
                    </span>
                  </span>
                </span>
              </span>
            </a>
          </div>
      </div>
  </div> -->
  </div>
</div>
<script src="{% static 'mainpage/js/mainpage.js' %}"></script>
{% endblock %}