accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

boxing/urls.py
from django.urls import path
from . import views

app_name = "boxing"

urlpatterns = [
    path('', views.boxing, name="menu"),
    path('tag/', views.tag, name="tag"),
    path('non_tag/', views.non_tag, name="nontag"),
    path('save_img/', views.save_img, name="save_img"),
    path('save_position/<int:image_pk>/', views.save_position, name="save_position"),
    path('save_tag_position/<int:image_pk>/', views.save_tag_position, name="save_tag_position"),
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
]

web_leb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('mainpage.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boxing/', include('boxing.urls')),
    path('taging/', include('taging.urls')),
    path('ranking/', include('ranking.urls')),
    path('yesorno/', include('yesorno.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_leb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lebeling</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap' rel='stylesheet' type='text/css'>
    {% block head %}
    {% endblock %}
    <style>
        @import url(https://fonts.googleapis.com/css?family=Dawning+of+a+New+Day|Sniglet:800|Monoton|Fredoka+One|Lobster);
        
        * {
            box-sizing: border-box;
        }
    
        body {
            background: #0f0f1c;
        }
        label{
            font-size: 1rem;
        }
    
        h1,
        h2,
        h3,
        h4 h5 {
            font-weight: normal;
        }
    
        header {
            width: 100%;
            padding: 2em 0.3em 0;
            color: #eee;
            text-align: center;
        }
    
        .content {
            width: 100%;
            height: 100%;
            padding: 0 3em;
            text-align: center;
        }
    
        .set {
            margin: 3em 0;
        }
    
        .tile {
            background: #222;
            display: flex;
            flex-direction: column;
            justify-content: center;
            text-align: center;
            color: #f7f3d2;
            border-radius: 0.1em;
            height: 10rem;
            line-height: 10rem;
        }
    
        .quiz {
            background: #7f9c80;
            border-bottom: 8px solid #506951;
            border-right: 8px solid #506951;
        }
    
        .speedgrader {
            background: #fef3ec;
            border-bottom: 8px solid #99403a;
            border-right: 8px solid #99403a;
        }
    
        .mobile {
            background: #c88d77;
            border-bottom: 8px solid #9c6551;
            border-right: 8px solid #9c6551;
        }
    
        .admin {
            background: #427c9e;
            border-bottom: 8px solid #2c607e;
            border-right: 8px solid #2c607e;
        }
    
        .module {
            background: #c5c09a;
        }
    
        .tile:hover {
            opacity: 0.9;
            color: #f7f3d2;
            text-decoration: none;
        }
    
        .retro {
            /* font: 400 64px/64px 'Fredoka One', sans-serif; */
            font: 64px/64px 'Black Han Sans', sans-serif;
            color: #f80;
            text-shadow: 0 2px 0 #292322,
                0 3px 0 #f4035f,
                0 4px 0 #f4035f,
                0 5px 0 #f4035f,
                0 6px 0 #f4035f;
            text-transform: uppercase;
        }

        .ranking {            
            color: #62ce7b;
        }

        .big{
            font: 64px/64px 'Black Han Sans', sans-serif;
        }

        .middle-size-font{
            font: 32px/32px 'Black Han Sans', sans-serif;
        }

        .small{
            font: 24px/24px 'Black Han Sans', sans-serif;
        }
    
        a {
            color: inherit;
        }
        a:hover{
            color: inherit;
            text-decoration: none;
        }

        img{
            margin: 3rem;
        }

        .teduri {
            border-width: 5px !important;
            border-radius: 30px !important;
        }

        .txtcenter {
             text-align: center;
         }
         .txtleft {
             text-align: left;
         }
    </style>
</head>
<body>
    {% if request.resolver_match.url_name == 'login' or request.resolver_match.url_name == 'signup' %}
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark mb-3">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <a class="nav-item nav-link text-white" href="{% url 'mainpage:index' %}">처음 화면</a>
          <div class="navbar-nav row ml-auto">
            {% if user.is_authenticated %}
                <!-- <a class="nav-item nav-link text-white" href="{% url 'mainpage:index' %}">CREATE</a> -->
                <a class="navbar-brand text-white" href="{% url 'mainpage:index' %}">{{ user.username }} 님 </a>
                <a class="nav-item nav-link text-danger" href="{% url 'accounts:logout' %}">Logout</a>
                
            {% else %}
                <a class="nav-item nav-link text-white" href="{% url 'accounts:login' %}">LogIn</a>
                <a class="nav-item nav-link text-white" href="{% url 'accounts:signup' %}">SignUp</a>
            {% endif %}
          </div>
        </div>
    </nav>
    {% endif %}
    <div class="container">
        {% block containerbody %}
        {% endblock %}
    </div>
    {% block body %}
    {% endblock %}
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>